### ISSUE TITLE
谢谢俣哲哥哥:-D

### ISSUE THREAD

**Issue by Hughshine** [gilsaia/NKThesis_bachelor_cc#1]
俣哲哥哥加油:-D

**Comment by gilsaia** [comment]
八说了 已经后悔了 简直重写一份

**Comment by Hughshine** [comment]
> 八说了 已经后悔了 简直重写一份

有时间俺也看看可不可以提个pr

**Comment by gilsaia** [comment]
> > 八说了 已经后悔了 简直重写一份
> 
> 有时间俺也看看可不可以提个pr

莫急 其实就是重新写了一份 我是打算等都写完了再传上来·的

**Comment by gilsaia** [comment]
完事 愿意帮忙可以提pr了（
